### ISSUE TITLE
Incorrect typing on AsyncResponse.iter_content()

### ISSUE THREAD

**Issue by judilsteve** [jawah/niquests#185]
One must run `async for chunk in await async_response.iter_content()` (which conflicts with the type hints provided for `AsyncResponse.iter_content()`) instead of the expected `async for chunk in async_response.iter_content()`.

## Expected Result

Content of the HTTP response to be printed in chunks to stdout.

## Actual Result

Exception:

```
Traceback (most recent call last):
  File "<redacted>/test.py", line 10, in <module>
    if __name__ == '__main__': asyncio.run(_main())
                               ^^^^^^^^^^^^^^^^^^^^
  File "/home/james/.pyenv/versions/3.12.1/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/james/.pyenv/versions/3.12.1/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/.pyenv/versions/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<redacted>/test.py", line 7, in _main
    async for chunk in resp.iter_content():
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
```

## Reproduction Steps

```python
import asyncio
from niquests import AsyncSession

async def _main():
    async with AsyncSession() as session:
        resp = await session.get('https://github.com/jawah/niquests', stream=True)
        async for chunk in resp.iter_content():
            print(chunk)

if __name__ == '__main__': asyncio.run(_main())
```

## System Information

    $ python -m niquests.help

```json
{
  "charset_normalizer": {
    "version": "3.4.0"
  },
  "http1": {
    "h11": "0.14.0"
  },
  "http2": {
    "jh2": "5.0.4"
  },
  "http3": {
    "enabled": true,
    "qh3": "1.2.1"
  },
  "idna": {
    "version": "3.10"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.12.1"
  },
  "niquests": {
    "version": "3.11.1"
  },
  "ocsp": {
    "enabled": true
  },
  "platform": {
    "release": "5.15.153.1-microsoft-standard-WSL2",
    "system": "Linux"
  },
  "system_ssl": {
    "version": "300000d0"
  },
  "urllib3.future": {
    "cohabitation_version": null,
    "version": "2.12.900"
  },
  "wassima": {
    "certifi_fallback": false,
    "enabled": true,
    "version": "1.1.5"
  }
}
```

## Workaround

```python
import asyncio
from niquests import AsyncSession
from typing import cast, Coroutine, AsyncGenerator

async def _main():
    async with AsyncSession() as session:
        resp = await session.get('https://github.com/jawah/niquests', stream=True)
        async for chunk in await cast(Coroutine[None, None, AsyncGenerator[bytes, None]], resp.iter_content()):
            print(chunk)

if __name__ == '__main__': asyncio.run(_main())
```

**Comment by Ousret** [comment]
It's true, something isn't right. But it is not what you think it is.
I suspect there's a bug (some edge case) that bring this bad UX. It does not seems to be something we can deal with within Niquests.

If you have a (rather clean, without breakage) solution that we can apply that makes both modern IDEs and mypy happy with, we'll proceed.

```python
async def reproducer() -> typing.AsyncGenerator[bytes, None]:
    async def gen() -> typing.AsyncGenerator[bytes, None]:
        yield b"foo"
        yield b"bar"
    return gen()
```

So there you have to `await reproducer()` as their is no `yield` within **reproducer**. This minimal code does not confuse mypy or IDEs. But Niquests makes it glitch somehow, making it "okay" to not await the method.

We'll need a typing expert to investigate.

Regards,

**Comment by gremlation** [comment]
I'm experiencing the same problem with `niquests==3.11.3`:

```python
async with niquests.AsyncSession() as session:
    response = await session.get(url, stream=True)
    async for chunk in await response.iter_content(chunk_size=4096):
```

This causes Pylance to generate the warning:

```
"AsyncGenerator[bytes, None]" is not awaitable
  "AsyncGenerator[bytes, None]" is incompatible with protocol "Awaitable[_T_co@Awaitable]"
    "__await__" is not presentPylance[reportGeneralTypeIssues](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportGeneralTypeIssues)
```

Could this be reopened @Ousret ?

**Comment by Ousret** [comment]
Could you share the exact environment you are in? IDE version, Pylance version?
FWIW I have no issue with PyCharm + Mypy at all. There was one before 3.11.3 but not anymore.

Does Pylance have a issue tracker? If so could you ask for their expertise on that matter?

Regards,

**Comment by IsaacsLab42** [comment]
I ran into the same issue and filed a bug report for Pylance. That was kicked over to pyright. They said they are going to issue a fix that will work around the somewhat ambiguous spec, but had a recommendation for a change that Niquests should implement. You can see the full thread at https://github.com/microsoft/pyright/issues/9969.

**Comment by Ousret** [comment]
Great. I suspected exactly that, they confirmed it. As for the recommendation, I already tried it, the issue remain the same with others type checker, some assume (hardcoded) that "async def" means -> "Coroutine" then whatever you specified.
So our definition actually (seems) is the most "compatible".

So, for anyone stumbling here:

Upgrade pyright to at least 1.1.395.

Regards,

**Comment by Ousret** [comment]
It should be. But as Pyright expert said, it is ambiguous and no official typing guidance exist for that exact case. We can't find a "right" way to do this immediately. 
Finally, given our limited time, I'd rather not dedicate time to that subject and remained focused around Niquests. If you want, you may ask for Mypy expertise and wisdom to get a second solid opinion.

regards,
