### ISSUE TITLE
HTTP3/QUIC does not work

### ISSUE THREAD

**Issue by jimf5** [jawah/niquests#52]
HTTP3/QUIC does not work

## Expected Result

Get response: HTTP 200 OK.

## Actual Result

  File "<input>", line 1, in <module>
    niquests.get("https://127.0.0.1:8443/", verify=False)
  File "/home/jim/venv/lib/python3.11/site-packages/niquests/api.py", line 169, in get
    return request(
           ^^^^^^^^
  File "/home/jim/venv/lib/python3.11/site-packages/niquests/api.py", line 106, in request
    return session.request(
           ^^^^^^^^^^^^^^^^
  File "/home/jim/venv/lib/python3.11/site-packages/niquests/sessions.py", line 449, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jim/venv/lib/python3.11/site-packages/niquests/sessions.py", line 1031, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jim/venv/lib/python3.11/site-packages/niquests/adapters.py", line 738, in send
    raise ConnectionError(e, request=request)
niquests.exceptions.ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=8443): Max retrie
s exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object
at 0x7f895d34d090>: Failed to establish a new connection: [Errno 111] Connection refused'))

## Reproduction Steps

```python
import niquests
niquests.get("https://127.0.0.1:8443/", verify=False) 
```

## System Information

    $ python -m niquests.help

```json
{
  "charset_normalizer": {
    "version": "3.3.2"
  },
  "cryptography": {
    "version": "41.0.5"
  },
  "http1": {
    "h11": "0.14.0"
  },
  "http2": {
    "h2": "4.1.0"
  },
  "http3": {
    "enabled": true,
    "qh3": "0.14.0"
  },
  "idna": {
    "version": "3.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.11.6"
  },
  "niquests": {
    "version": "3.3.4"
  },
  "ocsp": {
    "enabled": true
  },
  "platform": {
    "release": "6.1.21.2-microsoft-standard-WSL2",
    "system": "Linux"
  },
  "system_ssl": {
    "version": "300000a0"
  },
  "urllib3.future": {
    "version": "2.3.901"
  },
  "wassima": {
    "certifi_fallback": false,
    "enabled": true,
    "version": "1.0.3"
  }
}
```

I use nginx at localhost:8443:
```
$ netstat -unlp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 127.0.0.1:8443          0.0.0.0:*                           2648968/nginx: mast

```

**Comment by jimf5** [comment]
I appreciate your help. Here is out:
```
2023-12-07 23:12:01,003 | DEBUG | Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=None, status=None)
2023-12-07 23:12:01,004 | DEBUG | Converted retries value: 0 -> Retry(total=0, connect=None, read=None, redirect=None, status=None)
2023-12-07 23:12:01,006 | DEBUG | Starting new HTTPS connection (1): 127.0.0.1:8443
2023-12-07 23:12:01,009 | DEBUG | [797b36e4f85ceef9] TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
2023-12-07 23:12:01,012 | DEBUG | [797b36e4f85ceef9] QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
2023-12-07 23:12:01,013 | DEBUG | [797b36e4f85ceef9] TLS State.CLIENT_EXPECT_SERVER_HELLO -> State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS
2023-12-07 23:12:01,014 | DEBUG | [797b36e4f85ceef9] TLS State.CLIENT_EXPECT_ENCRYPTED_EXTENSIONS -> State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE
2023-12-07 23:12:01,016 | DEBUG | [797b36e4f85ceef9] TLS State.CLIENT_EXPECT_CERTIFICATE_REQUEST_OR_CERTIFICATE -> State.CLIENT_EXPECT_CERTIFICATE_VERIFY
2023-12-07 23:12:01,017 | DEBUG | [797b36e4f85ceef9] Discarding epoch Epoch.INITIAL
2023-12-07 23:12:01,026 | WARNING | [797b36e4f85ceef9] Error: 298, reason: self-signed certificate, frame_type: 6
2023-12-07 23:12:01,027 | DEBUG | [797b36e4f85ceef9] Connection close sent (code 0x12A, reason self-signed certificate)
2023-12-07 23:12:01,028 | DEBUG | [797b36e4f85ceef9] QuicConnectionState.CONNECTED -> QuicConnectionState.CLOSING
Traceback (most recent call last):
  File "<input>", line 3, in <module>
    s.get("https://127.0.0.1:8443/", verify=False)
  File "/home/jim/venv/lib/python3.11/site-packages/niquests/sessions.py", line 503, in get
    return self.request(
           ^^^^^^^^^^^^^
  File "/home/jim/venv/lib/python3.11/site-packages/niquests/sessions.py", line 449, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jim/venv/lib/python3.11/site-packages/niquests/sessions.py", line 1031, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jim/venv/lib/python3.11/site-packages/niquests/adapters.py", line 736, in send
    raise SSLError(e, request=request)
niquests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=8443): Max retries exceeded with url: / (Caused by SSLError('TLS over QUIC did not succeed (Error 298). Chain certifica
te verification failed.'))
```

**Comment by Ousret** [comment]
Thank you for the verbose output.
I looked and did find a bug.

Can you run:

```
pip install "git+https://github.com/jawah/urllib3.future.git@fix-quic-no-verify" -U 
```

And confirm whether or not it fix your issue.
